#!/usr/bin/env python3

import os
import sys

list_of_files = []

if len(sys.argv) < 2:
    sys.exit("missing path argument")

path = sys.argv[1]

if not os.path.exists(path):
    sys.exit("path does not exist: " + path)

path = os.getcwd() if len(sys.argv) == 1 else sys.argv[1]

print("cwd: ", os.getcwd())
print("arg: ", sys.argv)
print("path: ", os.path.basename(path))

for root, dirs, files in os.walk(os.getcwd()):
    for file in files:
        list_of_files.append(os.path.join(root, file))

for name in list_of_files:
    print(name)
